version: '3.1'
services:
    webserver:
            image: 'nginx:alpine'
            working_dir: /var/www/html
            volumes:
                - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
                - './nginx/nginx.conf:/etc/nginx/nginx.conf'
            ports:
                - '8080:80'
            networks:
            - smart_network
    db:
            image: mysql
            container_name: travellist-db
            restart: unless-stopped
            environment:
              MYSQL_DATABASE: ${DB_DATABASE}
              MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
              MYSQL_PASSWORD: ${DB_PASSWORD}
              MYSQL_USER: ${DB_USERNAME}
              SERVICE_TAGS: dev
              SERVICE_NAME: mysql
            volumes:
              - ./sql:/docker-entrypoint-initdb.d
            networks:
              - smart_network
    php-fpm:
        build: ./
        working_dir: /var/www/html
        networks:
            - smart_network

networks:
    smart_network:
        name: smart_network
